name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - ready_for_review
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is in draft mode
        if: github.event.pull_request.draft == true
        run: echo "Skipping CI because PR is still in draft mode" && exit 1

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Format
        run: pnpm run format

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is in draft mode
        if: github.event.pull_request.draft == true
        run: echo "Skipping CI because PR is still in draft mode" && exit 1

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck
